language: php
php:
    - 7.0
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
script: bin/phpunit -c phpunit.xml
notifications:
    on_success: never
    on_failure: always
